# Generated by Django 2.2.5 on 2022-01-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220113_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='checkin',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='checkout',
            new_name='check_out',
        ),
    ]
