# Generated by Django 2.2.5 on 2022-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
